### ISSUE TITLE
Issue in line 75 of main.py.

### ISSUE THREAD

**Issue by shivamkautilya** [furas/AutoDraw#1]
During compilation it throws error at line ` self.img = np.swapaxes(self.img, 0, 1)` in `main.py` file.
Compiler is showing folowing error :
` File "C:\Users\Shivam Raj\Downloads\AutoDraw-main\AutoDraw-main\main.py", line 354, in <module>
    ad = AutoDraw(image, screen_size=(1440,900))`
`File "C:\Users\Shivam Raj\Downloads\AutoDraw-main\AutoDraw-main\main.py", line 75, in __init__
    self.img = np.swapaxes(self.img, 0, 1)`
` File "<__array_function__ internals>", line 5, in swapaxes`
`File "C:\Python 39\lib\site-packages\numpy\core\fromnumeric.py", line 595, in swapaxes
    return _wrapfunc(a, 'swapaxes', axis1, axis2)`
`File "C:\Python 39\lib\site-packages\numpy\core\fromnumeric.py", line 55, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)`
`File "C:\Python 39\lib\site-packages\numpy\core\fromnumeric.py", line 44, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)`
`numpy.AxisError: axis1: axis 0 is out of bounds for array of dimension 0`

**Comment by furas** [comment]
I changed all filenames before sending on GitHub but there was old filename in code and this gives this problem.

It should be

    image = 'autodraw-image-1a.png'

---

If you want to test with own image then put it in `image = ...`. 
To make sure better uses `/full/path/to/image.png`

**Comment by shivamkautilya** [comment]
Thanks :)
